# Generated by Django 4.1 on 2022-09-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
